### ISSUE TITLE
Test runner does not work for some projects

### ISSUE THREAD

**Issue by oubiwann** [lfe-rebar3/rebar3_lfe_ltest#1]
See this issue:
- https://github.com/lfex/kla/issues/6

Also, the loise tests suffer from the same issue as that noted above.

**Comment by oubiwann** [comment]
Related issues and PRs:
- https://github.com/lfex/kla/issues/6
- https://github.com/erlang/rebar3/issues/1331
- In particular, this comment: https://github.com/erlang/rebar3/issues/1331#issuecomment-249454356
- https://github.com/lfe-rebar3/compile/pull/26

**Comment by oubiwann** [comment]
One thing I have noted that I find fairly distressing, and may actually represent the true symptom of the problem:
- when a project that has this issue is compiled and the tests are run (using the `as test` rebar3 profile for the projects), only the `plugins` directory is listed in `code:get_path`, not the `lib` directory. So whole chunks of code are missing.

This means that only the libraries listed in the profile's "plugins" section are in the code path, not the libraries that are listed in the "deps" section.

This could indicate the following root problem:
- one or more LFE plugins is not setting  the dependency paths correctly

or, less likely:
- rebar3 is not setting the dependency paths correctly when custom profiles are used

or, more likely than that:
- I have misunderstood the inner workings of this aspect of rebar3 plugins

**Comment by yurrriq** [comment]
I'll ask on #rebar re: plugins in profiles and report back.

**Comment by oubiwann** [comment]
Interestingly, I get the same issue when running with all three of the following:
- `DEBUG=1 rebar3 as test lfe test`
- `DEBUG=1 rebar3 as default,test lfe test`
- `DEBUG=1 rebar3 as default,dev,test lfe test`

No `lib` directory in `code:get_path` -- just the `plugins` directory.

**Comment by oubiwann** [comment]
@yurrriq: it's probably too soon to ping/bother them: I haven't eliminated LFE plugins as potential culprits ...

**Comment by yurrriq** [comment]
~~Does the general pattern `rebar3 as a,b,c task` work? I think that would run `task` as the profile `a,b,c` not as `a`, `b` and `c`.~~

**Comment by yurrriq** [comment]
I asked if including `plugins` under `profiles` is generally ok and pasted some links. If it is ok, then it's almost definitely a problem on the `lfe-rebar3` side... maybe `lfe-compile`.

**Update**:

> it's okay but the plugin will only be visible if you call rebar3 as profile plugin

**Comment by yurrriq** [comment]
Side note: I think we should probably `s/default/test/` [here](https://github.com/lfe-rebar3/test/blob/0.4.0-rc1/src/lfe-test.lfe#L8).

**Comment by oubiwann** [comment]
Here are the docs on profiles:
- https://www.rebar3.org/docs/profiles

They should how to use multiple profiles in a command there ...

**Comment by oubiwann** [comment]
Regarding `s/default/test/` ... I was just looking that up, since that caught my eye as well. I wasn't thinking replace, though, but addition.

Regardless, there are deps defined in the `test` profile I'm using, as well as the `default` profile ... so I'm not sure that this would be the problem behind only plugin deps showing up? Not sure ...

**Comment by yurrriq** [comment]
> They should how to use multiple profiles in a command there ...

Quite right.

```
Usage: rebar3 as [<profile>]

  <profile>  Profiles to run as.
```

**Comment by yurrriq** [comment]
> I'm not sure that this would be the problem behind only plugin deps showing up

I don't think so either.

**Comment by oubiwann** [comment]
On the docs page, be sure to see this example: `rebar3 as test,native ct`

**Comment by oubiwann** [comment]
And the ones like these `rebar3 as prod,native,test <command>` ...

**Comment by yurrriq** [comment]
For [elli_xpblfe](https://github.com/elli-lib/elli_xpblfe) with `lfe-compile` `0.7.0` instead of `0.6.0` (as is checked in):
```fish
rebar3 as test path -s '
'
```
```
/path/to/elli_xpblfe/_build/test/lib/ltest/ebin
/path/to/elli_xpblfe/_build/test/lib/elli/ebin
/path/to/elli_xpblfe/_build/test/lib/elli_xpblfe/ebin
```

-----

```fish
rebar3 as test shell
```
```erlang
1> code:get_path().
["/path/to/elli_xpblfe/_build/test/lib/elli_xpblfe/test",
 "/path/to/elli_xpblfe/_build/test/lib/elli_xpblfe/ebin",
 "/path/to/elli_xpblfe/_build/test/lib/elli/ebin",
 "/path/to/elli_xpblfe/_build/test/lib/ltest/ebin",
 "/path/to/elli_xpblfe/_build/test/lib/color/ebin",
 "/path/to/elli_xpblfe/_build/test/lib/lutil/ebin",
 "/path/to/elli_xpblfe/_build/test/lib/clj/ebin",
 "/path/to/elli_xpblfe/_build/test/lib/kla/ebin",
 "/path/to/elli_xpblfe/_build/test/lib/lfe-version/ebin",
 "/path/to/elli_xpblfe/_build/default/plugins/lfe-compile/ebin",
 "/path/to/elli_xpblfe/_build/default/plugins/exemplar/ebin",
 "/path/to/elli_xpblfe/_build/default/plugins/jsx/ebin",
 "/path/to/elli_xpblfe/_build/default/plugins/levaindoc/ebin",
 "/path/to/elli_xpblfe/_build/default/plugins/lfe/ebin",
 "/path/to/elli_xpblfe/_build/default/plugins/lutil/ebin",
 "/path/to/elli_xpblfe/_build/default/plugins/clj/ebin",
 "/path/to/elli_xpblfe/_build/default/plugins/kla/ebin",
 "/path/to/elli_xpblfe/_build/default/plugins/lfe-version/ebin",
 "/path/to/elli_xpblfe/_build/default/plugins/lodox/ebin"
 |...].
```

**Comment by oubiwann** [comment]
Ah, progress: by adding the compile plugin dep from the default namespace, I'm getting expected libs showing up:

``` cl
(defun deps () '(#(default app_discovery)
                 #(default compile)))
```

I'm still seeing errors with tests getting run, but this might be due to the regex fix not being used yet ... I'll test with that next.

**Comment by yurrriq** [comment]
Re: `test` deps, and setting the profile for this plugin to `test` instead of (or in addition to `default`), I'm nearly certain all deps from `default` will get symlinked into `_build/test/lib/`, so `test` essentially behaves as `default,test` anyway.

**Comment by yurrriq** [comment]
Note that the regex fix didn't work for me before, but it could have been a `_checkouts/`-related issued. I still needed to do `{eunit_compile_opts, [{src_dirs, ["src", "test"]}]}`.

**Comment by yurrriq** [comment]
Possibly related/helpful: https://github.com/rvirding/lfe/commit/fcdd4f9de5dce0eacde0ed9a24821ba697da77e0, namely the `app_compile` [hook](http://www.rebar3.org/docs/configuration#section-hookable-points-in-providers).

**Comment by oubiwann** [comment]
Debugging has confirmed that:
- the tests are being found
- they are being compiled to beam files
- the test runner is finding all the proper beam files for the given type of test (behaviour)

**Comment by oubiwann** [comment]
Okay, tests are passing now with the lte-test plugin running. The last bit was the fact that `eunit_compile_opts` either isn't supported by rebar3 or, if it is, that isn't being taken account in the LFE test or compile plugin. Regardless, by moving those compile opts into `erl_opts` in the test profile, the test running successfully finds all the files, runs them in eunit, and the tests pass again.

**Comment by yurrriq** [comment]
Nice! Weird about `eunit_compile_opts`. In my experience it works for `rebar3 [as whatever] eunit`.

**Comment by oubiwann** [comment]
`*sigh*`

Seems like there's still an issue:
- everything works great when running from scratch
- however, after a successful run, if run again without removing `_build`, all but the simplest test assertions
  fail

But this has given me an idea ...

**Comment by oubiwann** [comment]
Okay, looks like that idea got things fully working: I've added `#(lfe compile)` to the list of the plugin deps, which now read as the following:

``` cl
(defun deps () '(#(default app_discovery)
                 #(default compile)
                 #(lfe compile)
                 #(default lock)))
```

**Comment by oubiwann** [comment]
Okay, confirmed as working in loise and kla -- closing.
